# -*- coding: utf-8 -*-
"""ChuckNorisAPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ePxlhF4V4A7_g8Gu6WjVI_6MDWoq-Rnt
"""

import requests
import json

print("Welcome to Chuck Norris Joke App")
daily_joke = requests.get("https://api.chucknorris.io/jokes/random")
print(daily_joke.json())
print("The daily quote is: ", daily_joke.json()['value'])

jokes_categories = requests.get("https://api.chucknorris.io/jokes/categories")
#pass_time = requests.json()['categories']

categoList = json.loads(jokes_categories.text)

number = 1
print("Quote" Categories:")
for category in categoList:
  print(number, ".",category)
  number += 1

category_user = input("Please chooce a category\n")
params = {'categoty' : category_user}
search_joke_catego = requests.get('https://api.chucknorris.io/jokes/random?', params= params)
joke = search_joke_catego.json()['value']
print(f'Chuck Noris qoute for {category_user} is: {joke}')

import time

search_user = input("Enter any word that you wish to search\n")
params = {'query': search_user}
search_word = requests.get('https://api.chucknorris.io/jokes/search?', params = params)

searchList = json.loads(search_word.text)
searchList = searchList['result']

print(f'The result for the {search_user} are:')
for i in searchList:
  print(i['value'])
  time.sleep(1)

# to print a jason object 
def jprint(obj):
    # create a formatted string of the Python JSON object
    text = json.dumps(obj, sort_keys=True, indent=4)
    print(text)

jprint(search_word.json())
